FROM gw000/keras:2.1.4-py3


RUN python3 -m pip install tensorflow
RUN python3 -m pip install keras
RUN python3 -m pip install keras-rl
RUN python3 -m pip install gym
RUN python3 -m pip install numpy
RUN python3 -m pip install nose
RUN python3 -m pip install filelock
RUN python3 -m pip install Flask
RUN python3 -m pip install requests
RUN python3 -m pip install redis
RUN python3 -m pip install git+https://github.com/djaney/rl-http-agent.git