version: "3"
services:
  optimizer:
    tty: true
    build: .
    volumes:
      - .:/app
    entrypoint:
      - python3
      - /app/optimizer.py
    depends_on:
      - redis

  api:
    tty: true
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - FLASK_APP=/app/api.py
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    entrypoint:
      - flask
      - run
      - "--host=0.0.0.0"
    depends_on:
      - redis

  redis:
    image: redis:4.0.5-alpine
