version: "3"
services:
  api:
    tty: true
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_APP=/app/api.py
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    entrypoint:
      - flask
      - run
      - "--host=0.0.0.0"